name: yolo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.0.1
  - python=3.8.8
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - numpy==1.20.2
    - opencv-python==4.5.1.48
    - tqdm==4.60.0

